# Generated by Django 5.2.5 on 2025-11-01 02:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Sala')),
                ('tipo', models.CharField(choices=[('SALA', 'Sala de Aula'), ('LAB', 'Laboratório'), ('QUADRA', 'Quadra/Espaço Esportivo')], default='SALA', max_length=10)),
                ('capacidade', models.IntegerField(default=30)),
                ('recursos', models.TextField(blank=True, verbose_name='Recursos (Ex: Projetor, 30 PCs)')),
            ],
        ),
        migrations.AlterModelOptions(
            name='atividadependente',
            options={'ordering': ['data_limite'], 'verbose_name': 'Atividade Pendente', 'verbose_name_plural': 'Atividades Pendentes'},
        ),
        migrations.RemoveField(
            model_name='atividadependente',
            name='bimestre',
        ),
        migrations.RemoveField(
            model_name='atividadependente',
            name='disciplina',
        ),
        migrations.AddField(
            model_name='atividadependente',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default='2025-01-01 10:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atividadependente',
            name='data_limite',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atividadependente',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Em Andamento', 'Em Andamento'), ('Concluida', 'Concluída')], default='Pendente', max_length=20),
        ),
        migrations.AddField(
            model_name='atividadependente',
            name='titulo',
            field=models.CharField(default='Título Padrao Antigo', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livro',
            name='exemplares_disponiveis',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='livro',
            name='isbn',
            field=models.CharField(blank=True, max_length=17, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='atividadependente',
            name='descricao',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='livro',
            name='data_publicacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nota',
            name='disciplina',
            field=models.CharField(choices=[('LING', 'Linguagens'), ('CH', 'Ciências Humanas'), ('CN', 'Ciências da Natureza'), ('MAT', 'Matemática'), ('DS', 'Itinerário técnico')], max_length=4),
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlanejamentoSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turma', models.CharField(choices=[('1A', '1 ANO A'), ('1B', '1 ANO B'), ('1C', '1 ANO C'), ('2A', '2 ANO A'), ('2B', '2 ANO B'), ('2C', '2 ANO C'), ('3A', '3 ANO A'), ('3B', '3 ANO B'), ('3C', '3 ANO C')], max_length=2, verbose_name='Turma')),
                ('disciplina', models.CharField(max_length=100, verbose_name='Disciplina')),
                ('dia_semana', models.CharField(choices=[('SEG', 'Segunda-feira'), ('TER', 'Terça-feira'), ('QUA', 'Quarta-feira'), ('QUI', 'Quinta-feira'), ('SEX', 'Sexta-feira'), ('SAB', 'Sábado')], max_length=3, verbose_name='Dia da Semana')),
                ('data_aula', models.DateField(verbose_name='Data da Aula')),
                ('turno', models.CharField(choices=[('MANHA', 'Manhã'), ('TARDE', 'Tarde'), ('NOITE', 'Noite')], max_length=10, verbose_name='Turno')),
                ('horario_inicio', models.TimeField(verbose_name='Horário de Início')),
                ('horario_fim', models.TimeField(verbose_name='Horário de Término')),
                ('conteudo', models.TextField(verbose_name='Conteúdo Programado')),
                ('atividades', models.TextField(blank=True, verbose_name='Atividades Previstas')),
                ('recursos', models.TextField(blank=True, verbose_name='Recursos Necessários')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretaria.professor', verbose_name='Professor Responsável')),
            ],
            options={
                'verbose_name': 'Planejamento Semanal',
                'verbose_name_plural': 'Planejamentos Semanais',
                'ordering': ['data_aula', 'horario_inicio'],
                'unique_together': {('turma', 'data_aula', 'horario_inicio')},
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horario_inicio', models.TimeField()),
                ('horario_fim', models.TimeField()),
                ('finalidade', models.CharField(max_length=255, verbose_name='Finalidade da Reserva')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretaria.professor')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretaria.sala')),
            ],
            options={
                'verbose_name': 'Reserva de Sala',
                'verbose_name_plural': 'Reservas de Salas',
                'unique_together': {('sala', 'data', 'horario_inicio')},
            },
        ),
        migrations.DeleteModel(
            name='PagamentoPendente',
        ),
    ]
