# Generated by Django 5.2.5 on 2025-11-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0002_sala_alter_atividadependente_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='disciplina',
            field=models.CharField(choices=[('LING', 'Linguagens'), ('CH', 'Ciências Humanas'), ('CN', 'Ciências da Natureza'), ('MAT', 'Matemática'), ('DS', 'Itinerário técnico')], default='LING', max_length=4, verbose_name='Disciplina Principal'),
            preserve_default=False,
        ),
    ]
