# Generated by Django 5.2.5 on 2025-11-01 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0003_professor_disciplina'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='disciplina',
        ),
        migrations.CreateModel(
            name='AtribuicaoProfessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turma', models.CharField(choices=[('1A', '1 ANO A'), ('1B', '1 ANO B'), ('1C', '1 ANO C'), ('2A', '2 ANO A'), ('2B', '2 ANO B'), ('2C', '2 ANO C'), ('3A', '3 ANO A'), ('3B', '3 ANO B'), ('3C', '3 ANO C')], max_length=2, verbose_name='Turma')),
                ('disciplina', models.CharField(choices=[('LING', 'Linguagens'), ('CH', 'Ciências Humanas'), ('CN', 'Ciências da Natureza'), ('MAT', 'Matemática'), ('DS', 'Itinerário técnico')], max_length=4, verbose_name='Disciplina')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretaria.professor')),
            ],
            options={
                'verbose_name': 'Atribuição de Professor',
                'verbose_name_plural': 'Atribuições de Professores',
                'unique_together': {('turma', 'disciplina')},
            },
        ),
    ]
