# Generated by Django 5.2.5 on 2025-11-01 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0005_professor_disciplina_delete_atribuicaoprofessor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='faltas_aluno',
            field=models.PositiveIntegerField(default=0, verbose_name='Número de Faltas'),
        ),
    ]
