# Generated by Django 5.2.5 on 2025-11-01 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0006_alter_aluno_faltas_aluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='comentario_descritivo',
            field=models.TextField(blank=True, null=True, verbose_name='Comentário Descritivo do Aluno/Performance'),
        ),
    ]
