# Generated by Django 5.2.7 on 2025-11-01 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0007_aluno_comentario_descritivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='presencas_aluno',
            field=models.PositiveIntegerField(default=0, verbose_name='Número de Presenças'),
        ),
    ]
