# Generated by Django 5.2.7 on 2025-11-04 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0008_aluno_presencas_aluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
